{% set name = "pypeln" %}
{% set version = "0.4.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2819c62fe0e39b33fbdbdbec71b4b5b498ba99de240e536d749f87d7bd7b6f9e

build:
  number: 0
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pip
    - python
    - poetry
  run:
    - python
    - typing-extensions
    - dataclasses
    - stopit >=1.1.2,<2.0.0

test:
  imports:
    - pypeln
    - pypeln.process
    - pypeln.process.api
    - pypeln.sync
    - pypeln.sync.api
    - pypeln.task
    - pypeln.task.api
    - pypeln.thread
    - pypeln.thread.api
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://cgarciae.github.io/pypeln
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Concurrent data pipelines in Python

extra:
  recipe-maintainers:
    - pinin4fjords
