{% set name = "pypeln" %}
{% set version = "0.1.6" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: "1304a221de6b43257ba664f13a9dee5c97b7f40a7cbe7d7d839627c96dcf68fd"

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python
    - poetry
  run:
    - python
    - typing-extensions
    - dataclasses
    - stopit >=1.1.2,<2.0.0

test:
  imports:
    - pypeln
    - pypeln.process
    - pypeln.process.api
    - pypeln.sync
    - pypeln.sync.api
    - pypeln.task
    - pypeln.task.api
    - pypeln.thread
    - pypeln.thread.api
  requires:
    - pip
  commands:
   - pip check

about:
  home: "https://cgarciae.github.io/pypeln"
  license: "MIT"
  license_family: "MIT"
  license_file: LICENSE.txt
  summary: "Concurrent data pipelines in Python"

extra:
  recipe-maintainers:
    - pinin4fjords
